# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "findify-liquid"
client_id = "c8a5447ad3c3cb87c1f1e47f0ee3a070"
application_url = "https://whatever-metres-measurements-opposed.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://whatever-metres-measurements-opposed.trycloudflare.com/auth/callback",
  "https://whatever-metres-measurements-opposed.trycloudflare.com/auth/shopify/callback",
  "https://whatever-metres-measurements-opposed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "next-gen-integration.myshopify.com"
