version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/ruby:3.2.2-node

default-context: &default-context
  filters:
    branches:
      only:
        - main

orbs:
  trigger-pipeline: rundeck/trigger-pipeline@0.0.5

executors:
  node:
    docker:
      - image: cimg/ruby:3.2.2-node

commands:
  trigger_main_repository_pipeline:
    working_directory: ~/repo
    executor: node

    steps:
      - trigger-pipeline:
          debug: true
          token: "TBD"
          branch: "main"
          project-slug: "findify-liquid"

jobs:
  trigger_main_repository_pipeline:
    working_directory: ~/repo
    executor: node

    steps:
      - trigger-pipeline:
          debug: true
          token: "TBD"
          branch: "main"
          project-slug: "findify-liquid"

workflows:
  deploy_components:
    jobs:
      - trigger_main_repository_pipeline:
          <<: *default-context
