version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/ruby:3.2.2-node

default-context: &default-context
  filters:
    branches:
      only:
        - main

orbs:
  trigger-pipeline: rundeck/trigger-pipeline@0.0.5

executors:
  node:
    docker:
      - image: cimg/ruby:3.2.2-node

jobs:
  trigger_main_repository_pipeline:
    working_directory: ~/repo
    executor: node

    steps:
      - run:
          name: Trigger main repository pipeline
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/github/findify/findify-liquid/pipeline' \
            --header 'Content-Type: application/json' \
            -u $CIRCLECI_API_TOKEN

workflows:
  deploy_components:
    jobs:
      - trigger_main_repository_pipeline:
          <<: *default-context
